### ISSUE TITLE
Feature: The add-on is available at the NV Access add-on store

### ISSUE THREAD

**Issue by cary-rowen** [nvdaes/reportSymbols#7]
### Problem

The add-on is not published to the add-on store

### Suggestion

Hi,

Thanks for developing this add-on, someone was looking for it recently.

I have the following request. I would be very grateful if it could be fulfilled:

1. Collect the latest translations from SVN.
2. Publish a latest version to the NV Access add-on store

### Alternatives

I see that the Simplified Chinese translation is very old and has some errors, I would appreciate it if you could post a version with the latest translation.

**Comment by cary-rowen** [comment]
Additionally, the add-on is not available for download at https://addons.nvda-project.org/addons/reportSymbols.en.html.

**Comment by nvdaes** [comment]
Hello, I've published a version on the store with simplified Chinese today. Sorry for the late response. Thanks so much for your suggestion.
